steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.1.x
    inputs:
      packageType: sdk
      version: 3.1.x

  - task: DotNetCoreCLI@2
    displayName: Compile common code (amd64)
    inputs:
      command: build
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Linux$(configuration) -r linux-x64'
    
  - task: DotNetCoreCLI@2
    displayName: Compile common code (arm64)
    inputs:
      command: build
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Linux$(configuration) -r linux-arm64'

  - task: DotNetCoreCLI@2
    displayName: Run common unit tests
    inputs:
      command: test
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Linux$(configuration)'
      publishTestResults: true
      testRunTitle: 'Unit tests (Linux)'
