trigger:
  - master

variables:
  configuration: Release
  winImage: vs2017-win2016
  osxImage: macos-latest

jobs:
- job: windows
  displayName: Windows
  pool:
    vmImage: $(winImage)
  steps:
  - template: templates/windows/compile.yml
  - template: templates/windows/pack.yml

- job: osx
  displayName: macOS
  pool:
    vmImage: $(osxImage)
  steps:
  - template: templates/osx/compile.yml
  - template: templates/osx/pack.unsigned.yml

- job: ubuntu1804_x86_64
  displayName: Ubuntu 18.04 LTS x86_64
  pool:
    vmImage: ubuntu-18.04
  steps:
  - template: templates/linux/compile.yml
  - template: templates/linux/pack.unsigned.yml
